"""Application settings, loaded from .env once at import.

Everything is typed and validated at startup so a missing secret fails loudly
on boot rather than mysteriously on the first request.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

ROOT = Path(__file__).resolve().parents[2]


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=ROOT / ".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # Database
    #
    # DATABASE_URL is the APPLICATION connection and must be a role that is
    # neither superuser nor the table owner — normally `seoos_app`. RLS does not
    # apply to superusers at all, so an app connected as one reads every
    # organisation's rows with no error and no log line. See migration_url.
    database_url: str = Field(alias="DATABASE_URL")

    # Owner connection, for Alembic only. seoos_app deliberately lacks CREATE,
    # so migrations cannot run on DATABASE_URL. Blank falls back to it, which is
    # what a single-role setup (CI, throwaway test databases) wants.
    admin_database_url: str = Field(default="", alias="ADMIN_DATABASE_URL")

    # Secrets — generated by setup.sh
    token_encryption_key: str = Field(alias="TOKEN_ENCRYPTION_KEY")
    session_secret: str = Field(alias="SESSION_SECRET")

    # Google OAuth
    google_client_id: str = Field(default="", alias="GOOGLE_CLIENT_ID")
    google_client_secret: str = Field(default="", alias="GOOGLE_CLIENT_SECRET")

    # URLs
    api_url: str = Field(default="http://localhost:8000", alias="API_URL")
    web_url: str = Field(default="http://localhost:3000", alias="WEB_URL")

    # Ollama — local, $0
    ollama_host: str = Field(default="http://127.0.0.1:11434", alias="OLLAMA_HOST")
    ollama_model: str = Field(default="qwen3.5:9b", alias="OLLAMA_MODEL")
    ollama_embed_model: str = Field(default="nomic-embed-text", alias="OLLAMA_EMBED_MODEL")
    ollama_think: bool = Field(default=False, alias="OLLAMA_THINK")

    # Optional paid adapters — blank keeps the system at $0
    apify_token: str = Field(default="", alias="APIFY_TOKEN")
    remote_llm_api_key: str = Field(default="", alias="REMOTE_LLM_API_KEY")

    # App
    env: str = Field(default="dev", alias="ENV")
    log_level: str = Field(default="info", alias="LOG_LEVEL")

    @property
    def migration_url(self) -> str:
        """Connection for Alembic. Owner if configured, else the app role."""
        return self.admin_database_url or self.database_url

    @property
    def worker_database_url(self) -> str:
        """Connection for the worker's infrastructure queries.

        The queue and the scheduler are deliberately cross-tenant: claiming jobs
        is `FOR UPDATE SKIP LOCKED` over every org's rows, and scheduler.tick()
        scans all due schedules in one pass. Neither can run inside a
        tenant-scoped RLS context — under seoos_app both simply return zero rows
        and the nightly sync stops firing, silently.

        So the worker connects privileged and job handlers are responsible for
        entering tenant_tx() before touching tenant data. The API and the web
        app, which serve user requests, stay on the least-privilege role where
        RLS is the backstop.
        """
        return self.admin_database_url or self.database_url

    @property
    def is_prod(self) -> bool:
        return self.env == "prod-local"

    @property
    def cookie_secure(self) -> bool:
        """Whether the session cookie gets the Secure flag.

        Derived from the scheme, not from ENV. This system's production mode is
        still localhost over plain http, so keying Secure off `is_prod` would
        make the browser drop the session cookie the moment anyone ran
        `./run.sh --prod` — login would fail with no error anywhere. Put a TLS
        terminator in front and set API_URL to https, and this turns itself on.
        """
        return self.api_url.startswith("https://")

    @property
    def google_configured(self) -> bool:
        return bool(self.google_client_id and self.google_client_secret)

    @property
    def data_dir(self) -> Path:
        d = ROOT / "data"
        d.mkdir(exist_ok=True)
        return d

    @property
    def logs_dir(self) -> Path:
        d = ROOT / "logs"
        d.mkdir(exist_ok=True)
        return d


@lru_cache
def get_settings() -> Settings:
    return Settings()  # type: ignore[call-arg]


settings = get_settings()
